name: Example

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test docker build action
        uses: php-actions/test-docker-build-action@master
        with:
          php_version: "8.0"
          name: PHP Actions Example
